# Generated by Django 4.1.7 on 2023-03-12 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0016_order_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter_Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(choices=[('0 - 1000', '0 - 1000'), ('1000 - 2000', '1000 - 2000'), ('2000 - 3000', '2000 - 3000'), ('3000 - 4000', '3000 - 4000'), ('4000 - 5000', '4000 - 5000'), ('5000 - 10000', '5000 - 10000')], max_length=50)),
            ],
        ),
    ]
