# Generated by Django 4.1.4 on 2023-03-13 00:27

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0016_order_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
