# Generated by Django 4.1.5 on 2023-03-14 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0017_delivery_country_delivery_mobile'),
        ('eshop', '0017_filter_price'),
    ]

    operations = [
    ]
