# Generated by Django 4.1.5 on 2023-04-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0019_alter_review_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter_price',
            name='price',
        ),
        migrations.AddField(
            model_name='filter_price',
            name='max',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='filter_price',
            name='min',
            field=models.FloatField(null=True),
        ),
    ]
