# Generated by Django 4.1.5 on 2023-04-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0020_remove_filter_price_price_filter_price_max_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filter_price',
            options={'ordering': ['min', 'max'], 'verbose_name': 'Price bracket'},
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='tel',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
