# Generated by Django 4.1.5 on 2023-04-16 12:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0023_alter_arrival_details_options_alter_coupon_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'ordering': ['-delivered_at', '-state'], 'verbose_name_plural': 'deliveries'},
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivered_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
