# Generated by Django 4.1.5 on 2023-04-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0025_alter_payments_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alerts',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'alerts'},
        ),
        migrations.AlterField(
            model_name='alerts',
            name='traited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
