# Generated by Django 4.1.5 on 2023-04-16 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0026_alter_alerts_options_alter_alerts_traited_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqs',
            options={'verbose_name_plural': 'Faqs'},
        ),
        migrations.AlterModelOptions(
            name='filter_price',
            options={'ordering': ['min', 'max'], 'verbose_name': 'Price bracket', 'verbose_name_plural': 'Prices brackets'},
        ),
        migrations.AlterModelOptions(
            name='payments',
            options={'ordering': ['-payed_at', 'ref'], 'verbose_name_plural': 'payments'},
        ),
    ]
